name: Update-data
on:
  schedule:
    - cron: "30 16 * * 0" # Every Sunday at 4:30 PM

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@master # Set up R runtime
        with:
          r-version: 'release'
          
      - name: Setup renv # Set up R env to install packages
        run: |
          install.packages('remotes')
          remotes::install_github("rstudio/renv")
        shell: Rscript {0}
        
      - uses: actions/cache@v2 # Cache packages so won't be compiled everytime job is run
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install dependencies # Install the dependencies eg. Dplyr, tidyverse etc
        run: renv::restore()
        shell: Rscript {0}
  
      - name: Generate data # Run the script
        run: source("R/data_prep.R")
        shell: Rscript {0}